# -*- coding: utf-8 -*-
"""Bilingual content for the RSA website. Edit here, then run: python3 tools/build.py

Truth rules (see README): founder's selected works are academic designs or prior-employment
projects, never RSA commissions and never analysed with RSA. Status words must be accurate.
"""

# ---------------------------------------------------------------- site-wide facts
SITE = {
    'domain': 'https://rsa-analyzer.com',
    'email': 'research@rsa-analyzer.com',
}

# ---------------------------------------------------------------- UI strings
UI = {
    'en': {
        'skip': 'Skip to content',
        'status_l': 'RSA · Responsive Space Architecture',
        'status_r': '見築科技 · Taiwan · Vol. 01 / 2026',
        'brand_aria': 'RSA home',
        'brand_sub': 'Responsive Space<br>Architecture',
        'menu': 'Menu', 'close': 'Close',
        'nav': [('work.html', 'Work'), ('index.html#expertise', 'Expertise'), ('platform.html', 'Platform'),
                ('research.html', 'Research'), ('company.html', 'About'), ('contact.html', 'Contact')],
        'lang_switch': '繁中', 'lang_switch_lang': 'zh-Hant',
        'foot_lead': 'Understand the environment. Shape the future.',
        'foot_sub': 'RSA is an architecture and environmental-technology brand from Taiwan, connecting spatial design, site analysis and its own software research.',
        'foot_cols': [('Explore', [('work.html', 'Work'), ('platform.html', 'Platform'), ('research.html', 'Research')]),
                      ('RSA', [('company.html', 'About'), ('contact.html', 'Contact'), ('privacy.html', 'Privacy')])],
        'foot_lang': 'Language',
        'legal': ('Selected works are the founder’s academic designs and prior-employment projects. They are not RSA commissions and were not analysed with RSA. '
                  'Residential Site Analyzer is a research prototype in development. RSA does not provide statutory architect services. '
                  'Academic background does not imply endorsement by any university.'),
        'work': 'Work', 'home': 'Home', 'case': 'Case', 'next': 'Next',
        'credit_title': 'Project credit',
        'credit_academic': 'This is the founder’s individual academic design, not a project contracted or completed by RSA. No RSA-based environmental analysis is claimed for this project. Images are design visualisations, not photographs of a built project.',
        'credit_employment': 'This is the founder’s prior-employment experience: work performed for a former employer, not an RSA commission. No RSA-based environmental analysis is claimed for this project. Images are design visualisations of the project.',
        'k_year': 'Year', 'k_loc': 'Location', 'k_area': 'Area', 'k_type': 'Type', 'k_role': 'Role', 'k_context': 'Context',
        'approach': 'Design approach', 'connection': 'Connection to research', 'behind': 'Behind the work',
        'perspectives': 'Design perspectives', 'renders': 'Design visualisations',
        'fig_hero': 'Design visualisation',
        'case_study': 'Case study',
        'role_h': 'The founder’s role', 'role_sub': 'Scope of work', 'outcome': 'Outcome',
        'role_note': 'This work was done by the founder while employed by a residential developer, before RSA was founded. RSA as a company had no role in this project. Statutory architectural design and sign-off were not part of this role.',
    },
    'zh': {
        'skip': '跳到主要內容',
        'status_l': 'RSA · 見築科技',
        'status_r': 'Responsive Space Architecture · 台灣 · 2026',
        'brand_aria': 'RSA 首頁',
        'brand_sub': '見築科技<br>Responsive Space Architecture',
        'menu': '選單', 'close': '關閉',
        'nav': [('work.html', '作品'), ('index.html#expertise', '專業領域'), ('platform.html', '技術平台'),
                ('research.html', '研究'), ('company.html', '關於'), ('contact.html', '聯絡')],
        'lang_switch': 'EN', 'lang_switch_lang': 'en',
        'foot_lead': '先見環境，再築未來。',
        'foot_sub': 'RSA 見築科技：結合建築與空間設計、基地環境分析與自主軟體研發的建築環境科技品牌。',
        'foot_cols': [('探索', [('work.html', '作品'), ('platform.html', '技術平台'), ('research.html', '研究')]),
                      ('RSA', [('company.html', '關於'), ('contact.html', '聯絡'), ('privacy.html', '隱私')])],
        'foot_lang': '語言',
        'legal': ('精選作品為創辦人的學術設計作品與過往任職專案參與，並非 RSA 承攬案，也未使用 RSA 進行分析。'
                  'Residential Site Analyzer 為開發中的研究原型。RSA 不提供依法須由建築師執行之簽證業務。'
                  '學術背景不代表任何大學之背書。'),
        'work': '作品', 'home': '首頁', 'case': '案例', 'next': '下一個',
        'credit_title': '作品歸屬',
        'credit_academic': '本作品為創辦人個人學術設計，並非 RSA 承攬或完成之專案，亦未宣稱使用 RSA 進行環境分析。圖片為設計模擬圖，非落成實景。',
        'credit_employment': '本案為創辦人過往任職期間之專案參與，屬前任職公司之工作，並非 RSA 承攬案，亦未宣稱使用 RSA 進行環境分析。圖片為該專案之設計模擬圖。',
        'k_year': '年份', 'k_loc': '地點', 'k_area': '面積', 'k_type': '類型', 'k_role': '角色', 'k_context': '背景',
        'approach': '設計策略', 'connection': '與研究的關聯', 'behind': '作品背後',
        'perspectives': '設計視角', 'renders': '設計模擬圖',
        'fig_hero': '設計模擬圖',
        'case_study': '閱讀案例',
        'role_h': '創辦人的角色', 'role_sub': '工作範圍', 'outcome': '成果',
        'role_note': '以上工作為創辦人任職於住宅開發公司期間所負責，時間早於 RSA 成立；RSA 公司本身未參與本案。法定建築設計與簽證不在此角色範圍內。',
    },
}

# ---------------------------------------------------------------- projects
# imgs: (file, ratio, {en: (alt, caption), zh: (alt, caption)})
PROJECTS = [
  dict(slug='vision', no='01', kind='academic',
       name={'en': 'Vision Art Gallery', 'zh': '視界美術館'}, alt_name={'en': '視界美術館', 'zh': 'Vision Art Gallery'},
       klabel={'en': 'Individual academic design', 'zh': '個人學術設計'},
       year='2021', area=None,
       loc={'en': 'Tainan, Taiwan', 'zh': '台南'},
       role={'en': 'Individual design (sole designer)', 'zh': '個人設計（唯一設計者）'},
       type={'en': 'Graduation project · Art gallery', 'zh': '大學畢業設計 · 美術館'},
       context={'en': 'University graduation project · Kun Shan University, Dept. of Spatial Design', 'zh': '大學畢業設計 · 崑山科技大學 空間設計系'},
       tag={'en': 'Architecture as an experience of perception.', 'zh': '讓建築成為一段觀看的經驗。'},
       approach={'en': 'An A-frame column system packs the lower floors into small, close-range rooms for sculpture, then widens floor by floor until the city itself becomes the exhibit. Ramps built into the slabs carry visitors upward without a clear moment of arrival.',
                 'zh': '以 A 字形柱系統作為結構與空間語彙：低樓層柱體密集，切分出尺度較小、拉近人與作品距離的展區；樓層越高柱距越開，觀看重心逐步從作品轉向城市。樓板中的坡道讓人在緩慢連續的移動中被帶往高處。'},
       connection={'en': 'Reading a place through movement, distance and light—rather than simply representing a building—later became the starting point for environmental-evidence research.',
                   'zh': '透過移動、距離與光線去「讀」一個場所，而不只是再現一棟建築——這後來成為環境證據研究的起點。'},
       hero=('vision-exterior', {'en': 'A low, layered gallery building rendered across a reflecting pond under an overcast sky', 'zh': '層疊樓板的美術館，倒映在陰天的水面上'}),
       imgs=[('vision-tower', 'ratio-34', {'en': ('Stacked, cantilevered concrete slabs with a ramp rising from the waterside', 'Slabs & ramps'), 'zh': ('層層出挑的混凝土樓板與自水岸升起的坡道', '樓板與坡道')}),
             ('vision-gallery', 'ratio-32', {'en': ('Dark sculpted concrete gallery hall with sculptures on several levels', 'Compressed lower floors'), 'zh': ('低樓層的混凝土展廳，雕塑分佈在不同高度', '緊湊的低樓層')}),
             ('vision-corridor', 'ratio-21', {'en': ('Narrow wedge-shaped concrete corridor framing a sculpture at its far end', 'Focal length'), 'zh': ('楔形混凝土走廊，盡頭框出一尊雕塑', '焦距')}),
             ('vision-passage', 'ratio-32', {'en': ('Long concrete room opening to a framed view of the water and hills', 'From works to city'), 'zh': ('長形展間向水面與山景開口', '從作品到城市')}),
             ('vision-sculpture', 'ratio-32', {'en': ('Sunken sculpture court lit by a circular oculus above a stepped plinth', 'Light from above'), 'zh': ('圓形天窗下的下沉雕塑廣場', '頂光')})]),
  dict(slug='corner', no='02', kind='academic',
       name={'en': 'Corner Library', 'zh': '角落圖書館'}, alt_name={'en': '角落圖書館', 'zh': 'Corner Library'},
       klabel={'en': 'Individual academic design', 'zh': '個人學術設計'},
       year='2020', area='220 m²',
       loc={'en': 'Tainan, Taiwan', 'zh': '台南 · 國華街與正興街口'},
       role={'en': 'Individual design (sole designer)', 'zh': '個人設計（唯一設計者）'},
       type={'en': 'Academic design · Neighbourhood library', 'zh': '學術設計 · 街角圖書館'},
       context={'en': 'Third-year final design project · Kun Shan University, Dept. of Spatial Design', 'zh': '大三期末設計 · 崑山科技大學 空間設計系'},
       tag={'en': 'A place to pause, read and belong.', 'zh': '找一個角落，安心停下來。'},
       approach={'en': 'People settle into corners: semi-enclosed, moderately scaled spots feel safer than the centre of a room. Seating towers and a timber truss merge structure, shelving and seating into one walkable reading system, so each reader can choose the height and distance that suits them.',
                 'zh': '人在尺度適中、有包覆感的「角落」裡，比在空間中央更容易專注與停留。設計以座位塔與桁架系統，把結構、書架與座位整合成可行走、可乘坐、可停留的閱讀系統，讓使用者依自身狀態選擇高度與距離。'},
       connection={'en': 'Small changes in light, enclosure and spatial scale can transform the way people experience a place.',
                   'zh': '光線、包覆感與尺度的細微差異，就能改變人對一個場所的感受。'},
       hero=('corner-exterior', {'en': 'Glass-fronted library corner building on a wet city street', 'zh': '雨後街角的玻璃立面圖書館'}),
       imgs=[('corner-portal', 'ratio-34', {'en': ('Tall timber-and-glass entrance hall with wide steps where people sit and read', 'Threshold'), 'zh': ('木構玻璃入口大廳與可坐可讀的大階梯', '入口')}),
             ('corner-reading', 'ratio-32', {'en': ('Timber lattice reading structure with people seated at different heights', 'Seating towers'), 'zh': ('木格構閱讀架，人們坐在不同高度', '座位塔')}),
             ('corner-underpass', 'ratio-21', {'en': ('Concrete passage with timber bleacher seating and a long window to the city', 'Street edge'), 'zh': ('清水模通道與木作階梯座位，長窗面向城市', '街道邊界')}),
             ('corner-shelves', 'ratio-32', {'en': ('Narrow timber corridor lined with tall bookshelves and steps', 'Focus & pause'), 'zh': ('兩側高書架的木作廊道', '專注與停留')}),
             ('corner-library', 'ratio-32', {'en': ('Double-height reading room with bookshelves, columns and soft seating', 'Everyday use'), 'zh': ('挑高閱覽室、書架與柔軟座椅', '日常使用')})]),
  dict(slug='encounter', no='03', kind='academic',
       name={'en': 'Encounter Treatment', 'zh': '相癒'}, alt_name={'en': '相癒', 'zh': 'Encounter Treatment'},
       klabel={'en': 'Individual academic design', 'zh': '個人學術設計'},
       year='2020', area='220 m²',
       loc={'en': 'Tanzi, Taichung', 'zh': '台中 · 潭子'},
       role={'en': 'Individual design (sole designer)', 'zh': '個人設計（唯一設計者）'},
       type={'en': 'Academic design · Disability welfare centre', 'zh': '學術設計 · 身心障礙福利服務中心'},
       context={'en': 'Entry, 14th TSID national student interior / spatial design competition', 'zh': '第 14 屆 TSID 全國室內／空間學生競圖 參賽作品'},
       tag={'en': 'Inclusive space for connection and wellbeing.', 'zh': '療癒，發生在相遇之中。'},
       approach={'en': 'People with disabilities, carers and visitors share one curving route instead of a corridor of separate rooms. Wheelchair dimensions set the path widths, turning radii and resting points, so accessibility generates the plan rather than being added to it.',
                 'zh': '以曲線動線串聯公共活動、復健與交流場域，避免傳統走廊式分區。依輪椅使用尺度重新檢視通行寬度、轉彎半徑與停留節點，讓無障礙成為空間生成的起點，而非附加條件。'},
       connection={'en': 'Comfort is both environmental and social; design should make human experience central.',
                   'zh': '舒適同時是環境的，也是社會的；設計應以人的經驗為中心。'},
       hero=('encounter-atrium', {'en': 'Warm, round central space with cloud-like ceiling discs and wheelchair users', 'zh': '圓形天花與曲線動線的公共空間'}),
       imgs=[('encounter-front', 'ratio-34', {'en': ('Reception area seen from the entrance, timber ceiling discs overhead', 'Arrival'), 'zh': ('從入口看向接待區，木質圓形天花', '抵達')}),
             ('encounter-hall', 'ratio-32', {'en': ('Curved glass-block wall and timber floor in a quiet circulation hall', 'Continuous route'), 'zh': ('玻璃磚曲牆與木地板的連續動線', '連續動線')}),
             ('encounter-lounge', 'ratio-21', {'en': ('Residential-scale lounge with soft seating and a ceiling fan', 'Care & comfort'), 'zh': ('住宅尺度的交誼空間', '照護與舒適')})]),
  dict(slug='futian', no='04', kind='employment',
       name={'en': 'Futian · Seven Residences', 'zh': '福田案 · 七戶透天住宅'}, alt_name={'en': '福田案 · 七戶透天住宅', 'zh': 'Futian · Seven Residences'},
       klabel={'en': 'Prior employment', 'zh': '過往任職專案'},
       year='2022–2025', area=None,
       loc={'en': 'Xinpu, Hsinchu', 'zh': '新竹 · 新埔'},
       role={'en': 'Developer-side project lead (founder, for a former employer)', 'zh': '開發端專案主要負責（創辦人，任職於前公司期間）'},
       type={'en': 'Residential · 7 townhouses', 'zh': '住宅 · 七戶透天'},
       context={'en': 'Seven townhouses · handed over February 2025', 'zh': '七戶透天 · 2025 年 2 月交屋'},
       tag={'en': 'Turning residential planning into built experience.', 'zh': '從規劃到交屋的完整一程。'},
       approach={'en': 'Leading the developer-side process from planning to handover: coordinating plans, elevations and details with the design team, construction interfaces and quality, buyer change requests, procurement and sales support.',
                 'zh': '開發端從前期規劃到交屋的全流程負責：與設計團隊整合平面、立面與細部，協調營造工種介面與品質，處理客變需求、採購提報與銷售支援。'},
       connection={'en': 'Closing the loop between design, site and sales showed how often site conditions surface too late—the gap RSA now studies.',
                   'zh': '在「設計—現場—銷售」之間建立資訊閉環時，常發現基地條件太晚才被看見——這正是 RSA 現在研究的落差。'},
       scope={'en': [('Project coordination', 'Cross-department collaboration and meeting integration'),
                     ('Design integration', 'Plans, elevations and details, coordinated with the design team'),
                     ('Construction coordination', 'Trade interfaces and quality control on site'),
                     ('Buyer changes', 'Requirements and changes from buyers, folded back into planning'),
                     ('Sales support', 'Product positioning and after-sales process'),
                     ('Procurement', 'Specifications, cost and progress reporting')],
              'zh': [('專案統籌', '跨部門協作、會議整合'),
                     ('設計整合', '與設計團隊協作平面、立面與細部'),
                     ('營造協調', '工種介面與品質控管'),
                     ('客變管理', '需求溝通與規劃整合'),
                     ('銷售支援', '產品定位與售後流程'),
                     ('採購提報', '規格統整、成本與進度回報')]},
       outcome={'en': 'Built a design–site–sales information loop that reduced gaps and errors, and carried the project from planning to handover while holding quality, schedule and budget.',
                'zh': '建立「設計—現場—銷售」資訊閉環，降低落差與錯誤；從規劃到交屋全流程主責，維持品質、進度與預算。'},
       hero=('futian-exterior', {'en': 'Four-storey grey stone townhouse block beside a planted street', 'zh': '灰色石材立面的四層透天住宅'}),
       imgs=[('futian-entry', 'ratio-34', {'en': ('Framed concrete gateway leading into a paved residential lane', 'Entry & threshold'), 'zh': ('混凝土門框引導進入社區巷道', '入口')}),
             ('futian-material', 'ratio-32', {'en': ('Stone, metal and timber façade detail between townhouses', 'Material'), 'zh': ('石材、金屬與木紋立面細部', '材料')}),
             ('futian-street', 'ratio-21', {'en': ('Townhouse terrace seen across a planted street edge', 'Street frontage'), 'zh': ('沿街植栽與透天住宅群', '街道立面')})]),
  dict(slug='datong', no='05', kind='employment',
       name={'en': 'Datong · Fifteen Residences', 'zh': '竹南大同十五戶住宅'}, alt_name={'en': '竹南大同十五戶住宅', 'zh': 'Datong · Fifteen Residences'},
       klabel={'en': 'Prior employment', 'zh': '過往任職專案'},
       year='2024–', area=None,
       loc={'en': 'Zhunan, Miaoli', 'zh': '苗栗 · 竹南'},
       role={'en': 'Developer-side project lead (founder, for a former employer)', 'zh': '開發端專案主要負責（創辦人，任職於前公司期間）'},
       type={'en': 'Residential · 15 townhouses', 'zh': '住宅 · 十五戶透天'},
       context={'en': 'Fifteen townhouses · building permit obtained (status as of early 2026)', 'zh': '十五戶透天 · 已取得建照（2026 年初狀態）'},
       tag={'en': 'Residential scale, materials and urban context.', 'zh': '住宅尺度、材料與街區脈絡。'},
       approach={'en': 'Early planning—product positioning, massing and plan strategy, cost and sequencing feasibility—followed by façade coordination: style, materials and proportion, with schedules, quality standards and coordination between design, sales and construction.',
                 'zh': '前期規劃：產品定位、量體與平面策略、成本與工序可行性；接著是外觀設計整合：立面風格、材料選擇與比例，並負責進度節點、品質標準與設計／代銷／工務之間的協調。'},
       connection={'en': 'The project reinforces the need to consider environmental and material realities at the earliest design stage.',
                   'zh': '這個專案再次說明：環境與材料的現實，必須在設計最早期就被考慮。'},
       scope={'en': [('Early planning', 'Product positioning, massing and plan strategy, cost and sequencing feasibility'),
                     ('Exterior design', 'Façade style, material selection, rhythm and proportion'),
                     ('Delivery management', 'Schedule milestones, quality standards, site communication and documents'),
                     ('Project integration', 'Single point of contact for design, sales agency and construction; issue tracking and decisions')],
              'zh': [('前期規劃', '產品定位、量體／平面策略討論、成本與工序可行性'),
                     ('外觀設計', '立面風格整合、材料選擇協作、視覺節奏與比例優化'),
                     ('執行管理', '進度節點規劃、品質標準建立、現場溝通與文件管理'),
                     ('專案整合', '設計／代銷／工務窗口整合，議題追蹤與決策落地')]},
       outcome={'en': 'Early planning completed; design coordination in progress; preparing for sales and construction (status as of early 2026).',
                'zh': '前期規劃完成、設計整協作進行中、銷售與施工準備階段（2026 年初狀態）。'},
       hero=('datong-exterior', {'en': 'Corner view of a grey townhouse terrace with angled roof profiles', 'zh': '斜屋頂輪廓的灰色透天住宅轉角'}),
       imgs=[('datong-facade', 'ratio-34', {'en': ('Row of townhouse façades with vertical timber fins', 'Façade rhythm'), 'zh': ('木紋垂直格柵的連續立面', '立面節奏')}),
             ('datong-street', 'ratio-32', {'en': ('Townhouse terrace along a street with parked cars', 'Urban context'), 'zh': ('沿街的透天住宅群', '街區脈絡')}),
             ('datong-streetwide', 'ratio-21', {'en': ('Wide street elevation of the full terrace', 'Elevation'), 'zh': ('完整街廓立面', '立面')})]),
]
